<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cashlog.Common\Cashlog.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR.Contracts" />
      <PackageReference Include="protobuf-net" />
    </ItemGroup>

</Project>
