<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Serilog.AspNetCore"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cashlog.Core.MessageHandlers\Cashlog.Core.MessageHandlers.csproj" />
        <ProjectReference Include="..\Cashlog.Core\Cashlog.Core.csproj"/>
        <ProjectReference Include="..\Cashlog.Messenger.Telegram\Cashlog.Messenger.Telegram.csproj" />
    </ItemGroup>

</Project>
