<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Cashlog.Common\Cashlog.Common.csproj" />
      <ProjectReference Include="..\Cashlog.Messenger\Cashlog.Messenger.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
      <PackageReference Include="Telegram.Bot" />
    </ItemGroup>

</Project>
