//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashlog.Common {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cashlog.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В группе ещё не начат ни один расчётный период.
        /// </summary>
        public static string BillingPeriodNotCreated {
            get {
                return ResourceManager.GetString("BillingPeriodNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первый аргумент должен быть числом.
        /// </summary>
        public static string CommandFirstArgMustBeANumber {
            get {
                return ResourceManager.GetString("CommandFirstArgMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное кол-во параметров для команды.
        /// </summary>
        public static string CommandWrongArgsCount {
            get {
                return ResourceManager.GetString("CommandWrongArgsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий должен быть от {0} до {1} символов.
        /// </summary>
        public static string CommentLengthWrong {
            get {
                return ResourceManager.GetString("CommentLengthWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление перевода было отменено.
        /// </summary>
        public static string MoneyTransferCanceled {
            get {
                return ResourceManager.GetString("MoneyTransferCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кто переводит?.
        /// </summary>
        public static string MoneyTransferSelectFrom {
            get {
                return ResourceManager.GetString("MoneyTransferSelectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кому переводит?.
        /// </summary>
        public static string MoneyTransferSelectTo {
            get {
                return ResourceManager.GetString("MoneyTransferSelectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление перевода было успешно совершено.\nПеревёл: {0}\nКому: {1}\nСумма: {2} руб..
        /// </summary>
        public static string MoneyTransferSuccess {
            get {
                return ResourceManager.GetString("MoneyTransferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен новый чек!\nОплатил: {0}\nСумма: {1} руб.\nДелится на: {2}.
        /// </summary>
        public static string NewReceiptAddedInfo {
            get {
                return ResourceManager.GetString("NewReceiptAddedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление чека было отменено.
        /// </summary>
        public static string NewReceiptCancel {
            get {
                return ResourceManager.GetString("NewReceiptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось прочитать чек с фотографии.
        /// </summary>
        public static string ParsePhotoError {
            get {
                return ResourceManager.GetString("ParsePhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой чек уже добавлен в БД.
        /// </summary>
        public static string ReceiptAlredyAdded {
            get {
                return ResourceManager.GetString("ReceiptAlredyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На кого делится чек?.
        /// </summary>
        public static string SelectConsumers {
            get {
                return ResourceManager.GetString("SelectConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кто оплатил чек?.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестная команда, попробуй команду /help.
        /// </summary>
        public static string UnknownCommandType {
            get {
                return ResourceManager.GetString("UnknownCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я не читаю сообщения, попробуй прислать мне фото или используй команду /help.
        /// </summary>
        public static string UnknownMessageFormat {
            get {
                return ResourceManager.GetString("UnknownMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неподдерживаемый тип сообщения.
        /// </summary>
        public static string UnknownMessageType {
            get {
                return ResourceManager.GetString("UnknownMessageType", resourceCulture);
            }
        }
    }
}
