//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashlog.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cashlog.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В группе ещё не начат ни один расчётный период.
        /// </summary>
        public static string BillingPeriodNotCreated {
            get {
                return ResourceManager.GetString("BillingPeriodNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый аргумент должен быть числом.
        /// </summary>
        public static string CommandFirstArgMustBeANumber {
            get {
                return ResourceManager.GetString("CommandFirstArgMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное кол-во параметров для команды.
        /// </summary>
        public static string CommandWrongArgsCount {
            get {
                return ResourceManager.GetString("CommandWrongArgsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий должен быть от {0} до {1} символов.
        /// </summary>
        public static string CommentLengthWrong {
            get {
                return ResourceManager.GetString("CommentLengthWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка....
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление перевода было отменено.
        /// </summary>
        public static string MoneyTransferCanceled {
            get {
                return ResourceManager.GetString("MoneyTransferCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто переводит?.
        /// </summary>
        public static string MoneyTransferSelectFrom {
            get {
                return ResourceManager.GetString("MoneyTransferSelectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому переводит?.
        /// </summary>
        public static string MoneyTransferSelectTo {
            get {
                return ResourceManager.GetString("MoneyTransferSelectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление перевода было успешно совершено.\nПеревёл: {0}\nКому: {1}\nСумма: {2} руб..
        /// </summary>
        public static string MoneyTransferSuccess {
            get {
                return ResourceManager.GetString("MoneyTransferSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлен новый чек!\nОплатил: {0}\nСумма: {1} руб.\nДелится на: {2}.
        /// </summary>
        public static string NewReceiptAddedInfo {
            get {
                return ResourceManager.GetString("NewReceiptAddedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление чека было отменено.
        /// </summary>
        public static string NewReceiptCancel {
            get {
                return ResourceManager.GetString("NewReceiptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочитать чек с фотографии.
        /// </summary>
        public static string ParsePhotoError {
            get {
                return ResourceManager.GetString("ParsePhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой чек уже добавлен в БД.
        /// </summary>
        public static string ReceiptAlreadyAdded {
            get {
                return ResourceManager.GetString("ReceiptAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На кого делится чек?.
        /// </summary>
        public static string SelectConsumers {
            get {
                return ResourceManager.GetString("SelectConsumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто оплатил чек?.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда, попробуй команду /help.
        /// </summary>
        public static string UnknownCommandType {
            get {
                return ResourceManager.GetString("UnknownCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не читаю сообщения, попробуй прислать мне фото или используй команду /help.
        /// </summary>
        public static string UnknownMessageFormat {
            get {
                return ResourceManager.GetString("UnknownMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподдерживаемый тип сообщения.
        /// </summary>
        public static string UnknownMessageType {
            get {
                return ResourceManager.GetString("UnknownMessageType", resourceCulture);
            }
        }
    }
}
